### ISSUE TITLE
xen virtual network interface missing destroy support

### ISSUE THREAD

**Issue by mato** [rumpkernel/rumprun-xen#14]
This means we cannot cleanly release interfaces at domU shutdown, affects the new rumpconfig code. Further, it means any calls to rump_pub_netconfig_ifdestroy() will crash the domU:

From the discussion:

    13:14 < pwwka> well, the xen virtual network interface is missing destroy support
    13:14 < pwwka> so that's another problem
    13:14 < pwwka> use virtio ;)
    13:17 < pwwka> https://github.com/rumpkernel/rumprun-xen/blob/master/rumphyper_net.c#L216-L228
    13:18 < pwwka> bonus points if you know which song those lyrics are from ;)
    13:19 < mato> 136             strlcpy(ifr.ifr_name, ifname, sizeof(ifr.ifr_name));
    13:19 < mato> (gdb) n
    13:19 < mato> 137             return wrapifioctl(in4so, SIOCIFDESTROY, &ifr, curlwp);
    13:19 < mato> (gdb) n
    13:19 < mato> Breakpoint 1, do_page_fault (regs=0x3df8c8, error_code=0) at traps.c:202
    13:19 < mato> (gdb) p/x regs->rip
    13:19 < mato> $2 = 0x1a1930
    13:19 < mato> (gdb) p rumpns_mutex_enter
    13:19 < mato> $3 = {<text variable, no debug info>} 0x1a1930 <mutex_enter>
    13:19 < mato> no idea ...
    13:21 < pwwka> no point in debugging that further before VIFHYPER_DYING/DESTROY are 
               implemented

**Comment by anttikantee** [comment]
Here's what happened when I ran it:

```
=== calling main() ===

Hello, world!
Sleeping 5s...
Goodbye, world!

=== main() returned 0 ===
close network: backend at /local/domain/0/backend/vif/228/0
rump kernel halting...
syncing disks... done
unmounting file systems...
unmounted rumpfs on / type rumpfs
unmounting done
halted
minios: halting, reason=0
```

Is that the expected output?

**Comment by mato** [comment]
Indeed, this appears to work now. I also tried de-configuring an interface owned by dhcp and that works too. So, what changed?

**Comment by mato** [comment]
As @anttikantee says, ENOCLUE. Merging this and we'll see if anything breaks for someone other than us.
