### ISSUE TITLE
Trivial program which uses SSE fails with GPF

### ISSUE THREAD

**Issue by mato** [rumpkernel/rumprun-xen#18]
The following trivial test program fails with GPF in `printf()`; the fault occurs on the first use of `MOVAPS` which is an SSE instruction:

    #include <math.h>
    #include <stdio.h> 
    #include <unistd.h>
    
    int main (int argc, char *argv[]) 
    {
        printf("%f\n", cos(1.0));
        sleep(5);
        return 0;
    }

Hypothesis: FPU and/or SSE are not being initialised by Mini-OS at all/correctly. Also, the `__libm_init()` constructor should probably be called?

See also https://lists.cam.ac.uk/pipermail/cl-mirage/2012-December/msg00008.html, different but similar issue.

**Comment by mato** [comment]
@anttikantee suggested building with -mno-sse as a workaround however this triggers failures during build of `sys/external/bsd/compiler_rt/dist/lib/builtins/x86_64/floatdidf.c`:

    (...)floatdidf.c:12:1: error: SSE register return with SSE disabled

Going to investigate why SSE insns are not working in the first place...

**Comment by anttikantee** [comment]
On 12/01/15 11:39, Martin Lucina wrote:
> @anttikantee suggested building with -mno-sse as a workaround however this triggers failures during build of `sys/external/bsd/compiler_rt/dist/lib/builtins/x86_64/floatdidf.c`:
>
>      (...)floatdidf.c:12:1: error: SSE register return with SSE disabled
>
> Going to investigate why SSE insns are not working in the first place...

Yea, doesn't sound like it's worth it trying to make libc build with 
-mno-sse if it doesn't want to...

**Comment by mato** [comment]
Found the problem: The x86-64 ABI mandates that (%rsp + 8) be a multiple of 16. GCC works with this, and SSE instruction operands were misaligned, causing the fault. Commit 7ac88bd4c6f I have pushed to the wip-stackabi branch fixes this for me on x86_64, not tested on x86_32.

Please review.,

**Comment by mato** [comment]
Updated the commit; experimentally testing SSE on x86-32 shows it already has a good enough alignment for the stack (16 bytes) so the change is not needed there.

**Comment by anttikantee** [comment]
Doesn't removing pushq $0 have the same effect?

Anyway, I'm not quite sure what's going on there.  %rsp should be 16 byte aligned upon entry (either that or PAGE_SIZE, depending on if it's a pthread thread or not).  If you can figure out where it gets non-16-byte-aligned before thread_start, would increase confidence in the fix.

**Comment by mato** [comment]
Yes, %rsp is 16 byte aligned. However the x86-64 ABI mandates that *(%rsp + 8)* must be 16-byte aligned at the point of entry into a user function (see section 3.2.2 of the ABI PDF). 

Removing the pushq $0 does have the same effect; however I'm not sure if it won't break something else...?

**Comment by anttikantee** [comment]
On 12/01/15 16:16, Martin Lucina wrote:
> Yes, %rsp is 16 byte aligned. However the x86-64 ABI mandates that *(%rsp + 8)* must be 16-byte aligned at the point of entry into a user function (see section 3.2.2 of the ABI PDF).

Yes I know that's the problem, you explained it very clearly.  That's 
why I'm trying to analyse why %rsp+8 being 16 byte aligned does _NOT_ 
hold before your patch, just to make sure we aren't masking bugs.

And I'm of course assuming thread_start is not a "user function".

> Removing the pushq $0 does have the same effect; however I'm not sure if it won't break something else...?

Not sure.  But if a thread can exit successfully with it removed, I'm 
almost certain it's not needed.

**Comment by mato** [comment]
Doh. Inspiration on the bus: The extra 8 bytes come from the %rip saved by 
the callq to the user thread fn in minios_entry_thread_starter.

**Comment by anttikantee** [comment]
On 12/01/15 17:06, Martin Lucina wrote:
> Doh. Inspiration on the bus: The extra 8 bytes come from the %rip saved by
> the callq to the user thread fn in minios_entry_thread_starter.

Yes, probably.  That's what I too concluded some time ago (see above).

Fwiw, NetBSD does this:

```
         sp = (void **) (((uintptr_t)(stack_base + stack_size) & ~15));

         /* LINTED __greg_t is safe */
         gr[_REG_RDI] = (__greg_t)arg;
         *--sp = (void *) _lwp_exit;

         /* LINTED uintptr_t is safe */
         gr[_REG_URSP] = (uintptr_t) sp;
```

Can't see any 0 pushed onto the top of the stack.

**Comment by mato** [comment]
I've found the source of the `pushq $0`, it is this commit to xen.git: http://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=bb44bead1012120e08e81ce206612618384481de;hp=8d71c3dfb8f23ff68a03e6640cc4a8c40d25ea99

We agree that the extra 8 bytes come from the `callq` -- sorry, Github comment by email ate the last line of your comment where you mention it which I why I did not notice it. 

If we want to keep the 0 as end-of-backtrace marker then I suggest just adding another `pushq $0` to correct the alignment. I've tested this and it works fine.

Also, do we care about anyone running SSE (by accident, eg. via libc as we saw from printf) during Mini-OS boot? If so then I should probably fixup the initial SP value in the call from `_start` to `start_kernel`?

**Comment by anttikantee** [comment]
On 13/01/15 16:34, Martin Lucina wrote:
> I've found the source of the `pushq $0`, it is this commit to xen.git: http://xenbits.xen.org/gitweb/?p=xen.git;a=commitdiff;h=bb44bead1012120e08e81ce206612618384481de;hp=8d71c3dfb8f23ff68a03e6640cc4a8c40d25ea99
>
> We agree that the extra 8 bytes come from the `callq` -- sorry, Github comment by email ate the last line of your comment where you mention it which I why I did not notice it.
>
> If we want to keep the 0 as end-of-backtrace marker then I suggest just adding another `pushq $0` to correct the alignment. I've tested this and it works fine.

Cool, thanks for getting to the bottom of things and fixing them too.

> Also, do we care about anyone running SSE (by accident, eg. via libc as we saw from printf) during Mini-OS boot? If so then I should probably fixup the initial SP value in the call from `_start` to `start_kernel`?

Probably not, but it's such a cheap fix that we shouldn't debate if it's 
required or not and just fix it.

**Comment by mato** [comment]
Just checked the `_start` case, no change needed there as it does not do the terminate-the-backtrace stuff, so we're good to go as-is. Merging the branch.

**Comment by mato** [comment]
I just checked if this can be upstreamed and it has already been done there: mirage/xen@750cdc32d73f8d5e4e1cbd1f252dd145e8e8c962. So our trees are diverging :-(

**Comment by anttikantee** [comment]
On 15/01/15 11:12, Martin Lucina wrote:
> I just checked if this can be upstreamed and it has already been done there: mirage/xen@750cdc32d73f8d5e4e1cbd1f252dd145e8e8c962. So our trees are diverging :-(

well caught, i was looking just at thread_starter
