### ISSUE TITLE
Implement sincos() GCC builtin function

### ISSUE THREAD

**Issue by mato** [rumpkernel/rumprun-xen#20]
While testing PHP it was found that $RANDOM_EXTENSION uses combinations of calls to `sin()` and `cos()` which the host (Linux) GCC will optimize to calls to a `sincos()` function.

See also GCC PR#46926: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=46926

Current workaround is to specify `-fno-builtin-sin` and `-fno-builtin-cos` when building, we should implement a sincos() function in our libm similar to what eg. the Android folks do: https://android.googlesource.com/platform/bionic/+/android-4.4_r1/libm/sincos.c

Note this will affect other software using FP which calls to libm as our libm is not currently built with these flags and thus contains undefined refs to `sincos()`.

**Comment by anttikantee** [comment]
Why don't we just add the -fno-whatever to app-tools specs?  I don't see a reason to diverge from NetBSD.  If you feel strongly about this, I think the right way is to file a NetBSD PR about sincos and have the discussion there.

**Comment by justincormack** [comment]
sincos is basically pointless except on old x86 using the old style i387 fp where there is a sincos instruction. Otherwise, like android, it just calls both with no speedup.

**Comment by mato** [comment]
In order to be sure what `-fno-builtin-sin -fno-builtin-cos` does I checked the code generated by GCC (Debian jessie version) when building a test program. It looks like the flags are safe to use, the compiler generates code with normal calls to the libm `sin()` and `cos()`.

I'll make the change to the app-tools specs and also buildxen.sh since libm needs to be compiled with the same flags.

**Comment by mato** [comment]
Fixed, had to add flags for sinf and cosf also. Verified that rumpobj/lib/libm/libm.a no longer references these symbols.
